source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.0"

target "CollectionViewExample" do
  pod 'ObjectiveSugar', '~> 1.1'
end

target "CollectionViewExampleTests", exclusive: true do
    pod 'Specta',      '~> 0.2.1'
    pod 'Expecta',     '~> 0.3.0'
    pod 'OCMockito',   '~> 1.3.0'
    pod 'OHHTTPStubs', '~> 3.1.5'
end

