require './lib/xctool'

PROJECT = 'CollectionViewExample'
WORKSPACE = "#{PROJECT}.xcworkspace" 
SCHEME = PROJECT

namespace :xctool do
  XCTool::ACTIONS.each do |action|
    desc "Runs xctool's #{action} action"
    task action do
      xctool.send(action)
    end
  end
end

task default: 'xctool:test'

def xctool
  @xctool ||= XCTool.new(WORKSPACE, SCHEME, {
    dry_run: ENV['DRY_RUN'] == 'true',
    verbose: ENV['VERBOSE'] == 'true'
  })
end